apiVersion: v1
kind: Service
metadata:
  namespace: customApp
  labels:
    app: custom-external
  name: custom-external
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: custom-external
  type: LoadBalancer
status:
  loadBalancer: {}
